export const FETCH_CLIENTS = 'FETCH_CLIENTS';
export const FETCH_CLIENT = 'FETCH_CLIENT';
export const FETCH_CLIENTS_SUCCESS = 'FETCH_CLIENTS_SUCCESS';
export const FETCH_CLIENT_SUCCESS = 'FETCH_CLIENT_SUCCESS';
export const FETCH_CLIENTS_ERROR = 'FETCH_CLIENTS_ERROR';
export const FETCH_CLIENT_ERROR = 'FETCH_CLIENT_ERROR';
